version: "3.8"
services:
  api:
    build: .
    container_name: gonah
    ports:
      - "8877:8877"
    environment:
      GONAH_DB_DSN: postgres://pguser:pgpwd@db:5432/pgdb?sslmode=disable&pool_max_conns=10
      GONAH_KAFKA_HOST: kafka:9092
      GONAH_APIPORT: 8877
    networks:
      - shit_net
    depends_on:
      - db
      - kafka

  db:
    image: postgres:15.4
    container_name: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
    environment:
      POSTGRES_DB: "pgdb"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpwd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - dat:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - shit_net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.93.4
    depends_on:
      - victoriametrics
    ports:
      - "8429:8429"
    volumes:
      - vmagentdata:/vmagentdata
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - shit_net
    restart: always

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.93.4
    ports:
      - "8428:8428"
      - "8089:8089"
      - "8089:8089/udp"
      - "2003:2003"
      - "2003:2003/udp"
      - "4242:4242"
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"
    networks:
      - shit_net
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.7
    depends_on:
      - victoriametrics
    ports:
      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./docker/provisioning/:/etc/grafana/provisioning/
      - ./dashboards/pizdec.json:/var/lib/grafana/dashboards/pizdec.json
      - ./dashboards/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
      - ./dashboards/victorialogs.json:/var/lib/grafana/dashboards/vl.json
      - ./dashboards/vmagent.json:/var/lib/grafana/dashboards/vmagent.json
      - ./dashboards/vmalert.json:/var/lib/grafana/dashboards/vmalert.json
    networks:
      - shit_net
    restart: always

  vmalert:
    container_name: vmalert
    image: victoriametrics/vmalert:v1.93.4
    depends_on:
      - victoriametrics
      - alertmanager
    ports:
      - "8880:8880"
    volumes:
      - ./docker/alerts.yml:/etc/alerts/alerts.yml
      - ./docker/alerts-health.yml:/etc/alerts/alerts-health.yml
      - ./docker/alerts-vmagent.yml:/etc/alerts/alerts-vmagent.yml
      - ./docker/alerts-vmalert.yml:/etc/alerts/alerts-vmalert.yml
    command:
      - "--datasource.url=http://victoriametrics:8428/"
      - "--remoteRead.url=http://victoriametrics:8428/"
      - "--remoteWrite.url=http://victoriametrics:8428/"
      - "--notifier.url=http://alertmanager:9095/"
      - "--rule=/etc/alerts/*.yml"
      # display source of alerts in grafana
      - "--external.url=http://127.0.0.1:3000" #grafana outside container
      # when copypaste the line be aware of '$$' for escaping in '$expr'
      - '--external.alert.source=explore?orgId=1&left={"datasource":"VictoriaMetrics","queries":[{"expr":{{$$expr|jsonEscape|queryEscape}},"refId":"A"}],"range":{"from":"now-1h","to":"now"}}'
    networks:
      - shit_net
    restart: always

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.25.0
    volumes:
      - ./docker/alertmanager.yml:/config/alertmanager.yml
    command:
      - "--config.file=/config/alertmanager.yml"
    ports:
      - "9095:9093" # conflict with kafka controller
    networks:
      - shit_net
    restart: always

  fluentbit:
    container_name: fluentbit
    image: cr.fluentbit.io/fluent/fluent-bit:2.1.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./docker/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - victorialogs
    ports:
      - "5140:5140"
    networks:
      - shit_net

  victorialogs:
    container_name: victorialogs
    image: docker.io/victoriametrics/victoria-logs:v0.3.0-victorialogs
    command:
      - "--storageDataPath=/vlogs"
      - "--httpListenAddr=:9428"
    volumes:
      - victorialogs-fluentbit:/vlogs
    ports:
      - "9428:9428"
    networks:
      - shit_net

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.5
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_dat:/bitnami
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - shit_net

#  registry:
#    image: registry:2
#    container_name: registry
#    restart: always
#    ports:
#      - "5000:5000"
#    environment:
#      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
#      REGISTRY_AUTH: htpasswd
#      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
#      REGISTRY_AUTH_HTPASSWD_PATH: /opt/docker-registry/auth/htpasswd
#    volumes:
#      - ./docker/registry/htpasswd:/opt/docker-registry/auth/htpasswd
#      - registry:/data

volumes:
  dat: {}
  vmdata: {}
  kafka_dat: {}
  vmagentdata: {}
  grafanadata: {}
  victorialogs-fluentbit: {}

networks:
  shit_net: {}
