name: run-tests
on: [push]
# on:
#  pull_request:
env:
  GO_VERSION: 1.21.1
  test:
    name: Run Tests
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: set up go ${{env.GO_VERSION}}
      uses: actions/setup-go@v1
      with:
        go-version: ${{env.GO_VERSION}}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: go build -o gonah
    - name: Test @ PostgreSQL
      run: go test -count=1 -v ./...
